import os
import google.generativeai as genai

class ImageAssistantService:
    def __init__(self):
        self.api_key = os.getenv("GEMINI_API_KEY")
        if self.api_key:
            genai.configure(api_key=self.api_key)
        
    def generate_text_content(self, business_details):
        """Step 1: Generate Post Content (Text Only)"""
        prompt = f"""
        You are an AI Business Growth Content Assistant.
        User Business/Product: {business_details}

        Generate ONLY TEXT in the following format:

        POST IDEA
        - Platform: Instagram
        - Post Type: Image Post
        - Goal: (Awareness / Engagement / Sales based on business details)

        CAPTION
        - Hook: (1 short attention-grabbing line)
        - Body: (2–3 simple, friendly lines)
        - CTA: (Clear and actionable)

        HASHTAGS
        - Provide 5–8 relevant hashtags

        IMAGE DESCRIPTION (TEXT ONLY)
        - Describe what the image should show visually
        - Do NOT generate an AI image prompt here
        - No camera jargon, just human language
        """
        
        try:
            model = genai.GenerativeModel('gemini-2.5-flash')
            response = model.generate_content(prompt)
            return response.text
        except Exception as e:
            raise Exception(f"Failed to generate text content: {str(e)}")

    def generate_image_prompts(self, post_content):
        """Step 2: Generate AI Image Prompt (Only after user approval)"""
        prompt = f"""
        Based on the following social media post idea:
        {post_content}

        Generate an AI IMAGE GENERATION PROMPT and a NEGATIVE PROMPT.

        IMAGE PROMPT RULES:
        - Photorealistic
        - Clean background
        - Soft natural lighting
        - Minimal aesthetic
        - Lifestyle or product-focused
        - No text
        - No logos
        - No watermarks
        - Instagram-ready composition
        - Aspect ratio: 4:5

        NEGATIVE PROMPT RULES:
        - Blurry
        - Low resolution
        - Extra fingers
        - Distorted faces
        - Text artifacts
        - Watermarks
        - Logos

        Output ONLY:
        IMAGE PROMPT: [The Prompt]
        NEGATIVE PROMPT: [The Negative Prompt]
        """
        
        try:
            model = genai.GenerativeModel('gemini-2.5-flash')
            response = model.generate_content(prompt)
            return response.text
        except Exception as e:
            raise Exception(f"Failed to generate image prompts: {str(e)}")

    def generate_image(self, prompt):
        """Step 3: Generate actual image using Imagen (Gemini Image Model)"""
        try:
            # Using Imagen 3 for high-quality, photorealistic output
            model = genai.ImageGenerationModel("imagen-3.0-generate-001")
            
            # Generate the image synchronously
            response = model.generate_images(
                prompt=f"{prompt}, photorealistic, high resolution, 4:5 aspect ratio, soft natural lighting, minimal aesthetic",
                number_of_images=1,
                aspect_ratio="4:5",
                person_generation="allow_adult",
                safety_filter_level="block_some"
            )
            
            # Return image data as base64
            if response.images:
                image_bytes = response.images[0].image_bytes
                import base64
                return base64.b64encode(image_bytes).decode('utf-8')
            else:
                raise Exception("No image was generated by the model.")
                
        except Exception as e:
            print(f"Image Generation Error: {str(e)}")
            raise Exception(f"Failed to generate image: {str(e)}")

# Singleton instance
image_assistant_service = ImageAssistantService()
